fix(infra): Make actions work on Kaya-Home (#294)
* fix(preview): clean up without sudo and with docker

* fix: clean lockfile

* fix: removed all sudo cleans

* fix(env): required NEXT_PUBLIC_MEDIA_URL

* fix(test): added NEXT_PUBLIC_MEDIA_URL to env of frontend tests

* fix(importer): unique S3 constraint errors + added image dimensions

* fix: added garage to `depends_on` for backend + changed concurrency for production github action

* fix: removed need to copy garage for garage-init

* fix: removed pid from garage-init

* fix: clean package-lock

* fix: reverted garage-init back to alpine

diff --git a/.github/workflows/deploy-preview.yml b/.github/workflows/deploy-preview.yml
--- a/.github/workflows/deploy-preview.yml
+++ b/.github/workflows/deploy-preview.yml
@@ -37,12 +37,16 @@ jobs:
     needs: [run_backend_tests, run_frontend_tests]
 
     steps:
-      - name: Clean up runner directories
-        run: sudo chown -R $USER:$USER /opt/hostedtoolcache || true
-        continue-on-error: true
+      # We should not edit perms of this, if this breaks SSH into server and delete manually and let actions rebuild
+      # - name: Clean up runner directories
+      #  run: sudo chown -R $USER:$USER /opt/hostedtoolcache || true
+      #  continue-on-error: true
 
       - name: Clean up workspace
-        run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE || true
+        run: |
+          docker run --rm -v ${{ github.workspace }}:/workspace alpine sh -c "chown -R $(id -u):$(id -g) /workspace"
+        continue-on-error: true
+
       - name: Checkout repo
         uses: actions/checkout@v4
 
@@ -144,7 +148,10 @@ jobs:
     environment: preview
     steps:
       - name: Clean up workspace
-        run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE || true
+        run: |
+          docker run --rm -v ${{ github.workspace }}:/workspace alpine sh -c "chown -R $(id -u):$(id -g) /workspace"
+        continue-on-error: true
+
       - name: Checkout repo
         uses: actions/checkout@v4
 
